Update Ghibli data
Laboratoria/LIM015-data-lovers pull request #15
Opened 2021-07-16 21:32 UTC by AM27TH

Update ghibli.js and ghibli.json

2021-07-19 14:01 UTC, santiaguf requested changes

2021-07-19 14:01 UTC, santiaguf commented on src/data/ghibli/ghibli.js
> -          "img": "https://static.wikia.nocookie.net/studio-ghibli/images/d/d8/Zeniba.png",
@AM27TH por qué se borra a esta personaje?

2021-07-19 14:01 UTC, santiaguf commented on src/data/ghibli/ghibli.json
> -          "img": "https://static.wikia.nocookie.net/studio-ghibli/images/9/98/Aiuto_Gang_boss.jpg",
@AM27TH Por qué se borra a este personaje?

2021-07-19 14:06 UTC, AM27TH commented on src/data/ghibli/ghibli.json
> -          "img": "https://static.wikia.nocookie.net/studio-ghibli/images/9/98/Aiuto_Gang_boss.jpg",
El personaje esta repetido

2021-07-19 14:24 UTC, santiaguf commented on src/data/ghibli/ghibli.js
> -          "img": "https://static.wikia.nocookie.net/studio-ghibli/images/d/d8/Zeniba.png",
está repetido

2021-07-19 14:25 UTC, santiaguf approved these changes
Gracias por el pull request @AM27TH

2021-07-19 14:25 UTC, merged

2021-07-19 14:26 UTC, santiaguf commented
@AM27TH encontró unas correcciones para la data de Ghibli. cc @lupomontero @betsyvies

2021-07-27 20:29 UTC, santiaguf commented
@AM27TH tu PR fue aprobado en el repo original :) https://github.com/Laboratoria/bootcamp/pull/1084